### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by assertchris**

### CODE REVIEW

**Comment by assertchris** [comment]
Ok, I've removed PHPUnit as a dev dependency (same as in https://github.com/reactphp/whois/pull/6).

**Comment by assertchris** [comment]
@WyriHaximus ping

**Comment by WyriHaximus** [comment]
LGTM :+1: , also did a some checks and toyed around with it and works as intended :+1:

**Comment by WyriHaximus** [comment]
ping @cboden @clue

**Comment by assertchris** [comment]
Just pinging here to see if anybody with merge rights wants to settle this...

**Comment by clue** [comment]
LGTM :+1:

**Pull request closed without merging**
